name = "manyjulias"
uuid = "865a976e-521c-42f1-9481-16730d271c5f"
authors = ["Tim Besard <tim.besard@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
LibGit2_jll = "e37daf67-58a4-590a-8e99-b0245dd2ffc5"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
crun_jll = "aef68bef-9b3f-58c3-affd-5589e119eed3"
elfshaker_jll = "3654c272-9f13-50b0-a4d5-1f2e7e802f45"
